# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72e320805113e9a11a8f15f4c16c320be2739223a52c4493ab7e49b7dc534737d53b72d84f3d39fd3b50c3cd7de106d081ede6f5bfe8b8307f50680bc842ffd9

test:
  secret_key_base: c2c4e27019b1e00cbb5222275d2a301458caed74c25075a0748484e8a9288fabc30c5831eeb7bbaf3425a9349de25033ab7d59f2e01f9467fcac4816e89dc21b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
